#
# thinkfan.conf
#
# Specifically for my laptop's hardware
sensors:
  - hwmon: /sys/class/hwmon/hwmon9
    indices: [1]        # Package id 0 (most important)
  - hwmon: /sys/class/hwmon/hwmon8
    indices: [1]        # thinkpad EC CPU
  - hwmon: /sys/class/hwmon/hwmon4
    indices: [1]        # nvme composite

fans:
  - tpacpi: /proc/acpi/ibm/fan

levels:
  - [0,  0,  50]
  - [2, 48,  60]
  - [4, 58,  70]
  - [5, 68,  72]
  - [7, 72,  76]
  - [127, 76, 32767]
